version: 1 # format of this configuration file

module_version: 0.0.1

test_defaults:
  terraform_version: 1.5.7
  before_init: ["terraform fmt -check"]

tests:
  - name: build-test
    project_root: examples/simple-website

  # - name: test-all-features-and-subdomain
  #   project_root: examples/tests
  #   environment:
  #     TF_VAR_apex_domain: geotorus.org
  #     TF_VAR_subdomain: accounts

  # - name: test-no-cloudfront
  #   project_root: examples/tests
  #   environment:
  #     TF_VAR_apex_domain: geotorus.org
  #     TF_VAR_cf_dist: 0